- name: Create Directory for TLS Certificate and Key
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy TLS Certificate and Key
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - { dest: "/etc/nginx/ssl/fullchain.pem", src: "certs/isucon9.catatsuy.org/fullchain.pem" }
    - { dest: "/etc/nginx/ssl/privkey.pem", src: "certs/isucon9.catatsuy.org/privkey.pem" }

- name: Copy Nginx config
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Copy isucari Nginx config
  copy:
    src: etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-available/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - isucari.conf

- name: Enable isucari config
  file:
    path: /etc/nginx/sites-enabled/isucari.conf
    src: /etc/nginx/sites-available/isucari.conf
    state: link
  notify:
    - reload nginx
