- name: Check Installed aliyun
  become: yes
  command: /usr/local/bin/aliyun version
  register: aliyun_version_output
  changed_when: aliyun_version_output is failed
  ignore_errors: true

- name: Debug aliyun_version_output
  debug:
    var: aliyun_version_output

- name: Download aliyun
  become: yes
  when: aliyun_version_output is failed or aliyun_version_output.stdout != "3.0.24"
  get_url:
    url: "https://aliyuncli.alicdn.com/aliyun-cli-linux-3.0.24-amd64.tgz"
    sha256sum: "9470f970818d40bc97ae9fee7294763c96c8dc335c51c92df3031ddb0862f175"
    dest: "/root/aliyun-cli-linux-3.0.24-amd64.tgz"
    force: yes

- name: Install aliyun
  become: yes
  unarchive:
    src: "/root/aliyun-cli-linux-3.0.24-amd64.tgz"
    dest: /usr/local/bin
    remote_src: yes

- name: Install check script
  become: yes
  copy:
    src: isucon-instance-checker.pl
    dest: /usr/local/bin/isucon-instance-checker
    owner: root
    group: root
    mode: 0755
